# Generated by Django 2.1.5 on 2019-01-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emaild',
            new_name='email',
        ),
    ]
